services:
  - type: web
    name: h-serverless-running
    envVars:
      - key: PORT
        value: "4005"
    startCommand: "docker compose up -d"
    instances:
      desiredCount: 3
    runtime: [node]
